### ISSUE TITLE
Missing/empty Glyphs

### ISSUE THREAD

**Issue by m4rc1e** [ThomasJockin/JosefinSansFont-master#4]
Please pull my request then get these fixed.

**Missing outlines in Roman:**
Light master's commaturnedabovecomb
Light master's commaaccentcomb.alt
Light master's apostrophemod
Light master's macronbelowcomba
Regular master's commaturnedabovecomb
Regular master's commaaccentcomb.alt
Regular master's apostrophemod
Regular master's macronbelowcomba
Bold master's commaturnedabovecomb
Bold master's commaaccentcomb.alt
Bold master's apostrophemod
Bold master's macronbelowcomba

**Missing outlines in Italic:**
Light Italic master's macronbelowcomba
Regular Italic master's macronbelowcomba
Bold Italic master's macronbelowcomba

**Regression (missing glyphs from previous release):**
mu
Delta

**Glyphs present in Roman but not Italic**
'acutecomb.case',
'Nhookleft',
'brevecomb.case',
'gravecomb.case',
'ij',
'ringcomb.case',
'dotlessj',
'periodcentered.loclCAT.case',
'ijacute',
'commaaccentcomb.case',
'ogonekcomb.case',
'f_ij',
'nhookleft',
'macronbelowcomb',
'macroncomb.case',
'breveinvertedcomb.case',
'brevebelowcomb.case',
'commaaccentcomb.alt',
'f_f_ij',
'cedillacomb.case',
'horncomb.case',
'dotbelowcomb.case',
'dotaccentcomb.case',
'dieresiscomb.case',
'tildecomb.case',
'napostrophe',
'f_f_i',
'IJacute',
'f_f_l',
'hookabovecomb.case',
'f_f',
'dblgravecomb.case',
'dieresisbelowcomb.case',
'periodcentered.loclCAT',
'circumflexcomb.case',
'hungarumlautcomb.case',
'macronbelowcomb.case',
'ohornhookaeabove',
'caroncomb.case'

**Glyphs which are present in Italic but not Roman**
Ucaron',
'ohornhookabove' 
'dz'

**Comment by ThomasJockin** [comment]
Thank you Marc for the heads up. Will correct on Friday.

**Comment by m4rc1e** [comment]
Closing this, was fixed today:

![screen shot 2017-06-06 at 16 49 59](https://user-images.githubusercontent.com/7525512/26838504-36ffe8f2-4ad8-11e7-9c0a-9dd841357d31.png)
